name: Lint
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  checks: write
  contents: read

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          level: warning
          path: .
          pattern: '*.sh'
          fail_on_error: true
      - name: Run hadolint (Haskell Dockerfile Linter)
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          hadolint_ignore: DL3016 DL3018 # Ignore pinning apk and npm packages to specific version with @
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
